/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/sign-up/index'
import { Route as MainPenghuniNotificationRouteImport } from './routes/_main/penghuni/notification'
import { Route as MainPemilikNotificationRouteImport } from './routes/_main/pemilik/notification'
import { Route as AuthSignUpKtpRouteImport } from './routes/_auth/sign-up/ktp'
import { Route as AuthSignUpFormRouteImport } from './routes/_auth/sign-up/form'
import { Route as MainPenghuniMainRouteRouteImport } from './routes/_main/penghuni/_main/route'
import { Route as MainPemilikMainRouteRouteImport } from './routes/_main/pemilik/_main/route'
import { Route as MainPenghuniOnboardingIndexRouteImport } from './routes/_main/penghuni/onboarding/index'
import { Route as MainPenghuniMainIndexRouteImport } from './routes/_main/penghuni/_main/index'
import { Route as MainPemilikMainIndexRouteImport } from './routes/_main/pemilik/_main/index'
import { Route as MainPenghuniMainTagihanRouteImport } from './routes/_main/penghuni/_main/tagihan'
import { Route as MainPenghuniMainProfileRouteImport } from './routes/_main/penghuni/_main/profile'
import { Route as MainPenghuniMainKeluhanRouteImport } from './routes/_main/penghuni/_main/keluhan'
import { Route as MainPemilikPenghuniFormRouteImport } from './routes/_main/pemilik/penghuni/form'
import { Route as MainPemilikPenghuniCreatedRouteImport } from './routes/_main/pemilik/penghuni/created'
import { Route as MainPemilikPenghuniChooseRoomRouteImport } from './routes/_main/pemilik/penghuni/choose-room'
import { Route as MainPemilikMainTagihanRouteImport } from './routes/_main/pemilik/_main/tagihan'
import { Route as MainPemilikMainProfileRouteImport } from './routes/_main/pemilik/_main/profile'
import { Route as MainPemilikMainInformasiRouteImport } from './routes/_main/pemilik/_main/informasi'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/_auth/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainPenghuniNotificationRoute =
  MainPenghuniNotificationRouteImport.update({
    id: '/penghuni/notification',
    path: '/penghuni/notification',
    getParentRoute: () => MainRoute,
  } as any)
const MainPemilikNotificationRoute = MainPemilikNotificationRouteImport.update({
  id: '/pemilik/notification',
  path: '/pemilik/notification',
  getParentRoute: () => MainRoute,
} as any)
const AuthSignUpKtpRoute = AuthSignUpKtpRouteImport.update({
  id: '/_auth/sign-up/ktp',
  path: '/sign-up/ktp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpFormRoute = AuthSignUpFormRouteImport.update({
  id: '/_auth/sign-up/form',
  path: '/sign-up/form',
  getParentRoute: () => rootRouteImport,
} as any)
const MainPenghuniMainRouteRoute = MainPenghuniMainRouteRouteImport.update({
  id: '/penghuni/_main',
  path: '/penghuni',
  getParentRoute: () => MainRoute,
} as any)
const MainPemilikMainRouteRoute = MainPemilikMainRouteRouteImport.update({
  id: '/pemilik/_main',
  path: '/pemilik',
  getParentRoute: () => MainRoute,
} as any)
const MainPenghuniOnboardingIndexRoute =
  MainPenghuniOnboardingIndexRouteImport.update({
    id: '/penghuni/onboarding/',
    path: '/penghuni/onboarding/',
    getParentRoute: () => MainRoute,
  } as any)
const MainPenghuniMainIndexRoute = MainPenghuniMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainPenghuniMainRouteRoute,
} as any)
const MainPemilikMainIndexRoute = MainPemilikMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainPemilikMainRouteRoute,
} as any)
const MainPenghuniMainTagihanRoute = MainPenghuniMainTagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => MainPenghuniMainRouteRoute,
} as any)
const MainPenghuniMainProfileRoute = MainPenghuniMainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainPenghuniMainRouteRoute,
} as any)
const MainPenghuniMainKeluhanRoute = MainPenghuniMainKeluhanRouteImport.update({
  id: '/keluhan',
  path: '/keluhan',
  getParentRoute: () => MainPenghuniMainRouteRoute,
} as any)
const MainPemilikPenghuniFormRoute = MainPemilikPenghuniFormRouteImport.update({
  id: '/pemilik/penghuni/form',
  path: '/pemilik/penghuni/form',
  getParentRoute: () => MainRoute,
} as any)
const MainPemilikPenghuniCreatedRoute =
  MainPemilikPenghuniCreatedRouteImport.update({
    id: '/pemilik/penghuni/created',
    path: '/pemilik/penghuni/created',
    getParentRoute: () => MainRoute,
  } as any)
const MainPemilikPenghuniChooseRoomRoute =
  MainPemilikPenghuniChooseRoomRouteImport.update({
    id: '/pemilik/penghuni/choose-room',
    path: '/pemilik/penghuni/choose-room',
    getParentRoute: () => MainRoute,
  } as any)
const MainPemilikMainTagihanRoute = MainPemilikMainTagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => MainPemilikMainRouteRoute,
} as any)
const MainPemilikMainProfileRoute = MainPemilikMainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainPemilikMainRouteRoute,
} as any)
const MainPemilikMainInformasiRoute =
  MainPemilikMainInformasiRouteImport.update({
    id: '/informasi',
    path: '/informasi',
    getParentRoute: () => MainPemilikMainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/pemilik': typeof MainPemilikMainRouteRouteWithChildren
  '/penghuni': typeof MainPenghuniMainRouteRouteWithChildren
  '/sign-up/form': typeof AuthSignUpFormRoute
  '/sign-up/ktp': typeof AuthSignUpKtpRoute
  '/pemilik/notification': typeof MainPemilikNotificationRoute
  '/penghuni/notification': typeof MainPenghuniNotificationRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/pemilik/informasi': typeof MainPemilikMainInformasiRoute
  '/pemilik/profile': typeof MainPemilikMainProfileRoute
  '/pemilik/tagihan': typeof MainPemilikMainTagihanRoute
  '/pemilik/penghuni/choose-room': typeof MainPemilikPenghuniChooseRoomRoute
  '/pemilik/penghuni/created': typeof MainPemilikPenghuniCreatedRoute
  '/pemilik/penghuni/form': typeof MainPemilikPenghuniFormRoute
  '/penghuni/keluhan': typeof MainPenghuniMainKeluhanRoute
  '/penghuni/profile': typeof MainPenghuniMainProfileRoute
  '/penghuni/tagihan': typeof MainPenghuniMainTagihanRoute
  '/pemilik/': typeof MainPemilikMainIndexRoute
  '/penghuni/': typeof MainPenghuniMainIndexRoute
  '/penghuni/onboarding/': typeof MainPenghuniOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/': typeof MainIndexRoute
  '/sign-up/form': typeof AuthSignUpFormRoute
  '/sign-up/ktp': typeof AuthSignUpKtpRoute
  '/pemilik/notification': typeof MainPemilikNotificationRoute
  '/penghuni/notification': typeof MainPenghuniNotificationRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/pemilik/informasi': typeof MainPemilikMainInformasiRoute
  '/pemilik/profile': typeof MainPemilikMainProfileRoute
  '/pemilik/tagihan': typeof MainPemilikMainTagihanRoute
  '/pemilik/penghuni/choose-room': typeof MainPemilikPenghuniChooseRoomRoute
  '/pemilik/penghuni/created': typeof MainPemilikPenghuniCreatedRoute
  '/pemilik/penghuni/form': typeof MainPemilikPenghuniFormRoute
  '/penghuni/keluhan': typeof MainPenghuniMainKeluhanRoute
  '/penghuni/profile': typeof MainPenghuniMainProfileRoute
  '/penghuni/tagihan': typeof MainPenghuniMainTagihanRoute
  '/pemilik': typeof MainPemilikMainIndexRoute
  '/penghuni': typeof MainPenghuniMainIndexRoute
  '/penghuni/onboarding': typeof MainPenghuniOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_main/': typeof MainIndexRoute
  '/_main/pemilik/_main': typeof MainPemilikMainRouteRouteWithChildren
  '/_main/penghuni/_main': typeof MainPenghuniMainRouteRouteWithChildren
  '/_auth/sign-up/form': typeof AuthSignUpFormRoute
  '/_auth/sign-up/ktp': typeof AuthSignUpKtpRoute
  '/_main/pemilik/notification': typeof MainPemilikNotificationRoute
  '/_main/penghuni/notification': typeof MainPenghuniNotificationRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_main/pemilik/_main/informasi': typeof MainPemilikMainInformasiRoute
  '/_main/pemilik/_main/profile': typeof MainPemilikMainProfileRoute
  '/_main/pemilik/_main/tagihan': typeof MainPemilikMainTagihanRoute
  '/_main/pemilik/penghuni/choose-room': typeof MainPemilikPenghuniChooseRoomRoute
  '/_main/pemilik/penghuni/created': typeof MainPemilikPenghuniCreatedRoute
  '/_main/pemilik/penghuni/form': typeof MainPemilikPenghuniFormRoute
  '/_main/penghuni/_main/keluhan': typeof MainPenghuniMainKeluhanRoute
  '/_main/penghuni/_main/profile': typeof MainPenghuniMainProfileRoute
  '/_main/penghuni/_main/tagihan': typeof MainPenghuniMainTagihanRoute
  '/_main/pemilik/_main/': typeof MainPemilikMainIndexRoute
  '/_main/penghuni/_main/': typeof MainPenghuniMainIndexRoute
  '/_main/penghuni/onboarding/': typeof MainPenghuniOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pemilik'
    | '/penghuni'
    | '/sign-up/form'
    | '/sign-up/ktp'
    | '/pemilik/notification'
    | '/penghuni/notification'
    | '/sign-up/'
    | '/pemilik/informasi'
    | '/pemilik/profile'
    | '/pemilik/tagihan'
    | '/pemilik/penghuni/choose-room'
    | '/pemilik/penghuni/created'
    | '/pemilik/penghuni/form'
    | '/penghuni/keluhan'
    | '/penghuni/profile'
    | '/penghuni/tagihan'
    | '/pemilik/'
    | '/penghuni/'
    | '/penghuni/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/'
    | '/sign-up/form'
    | '/sign-up/ktp'
    | '/pemilik/notification'
    | '/penghuni/notification'
    | '/sign-up'
    | '/pemilik/informasi'
    | '/pemilik/profile'
    | '/pemilik/tagihan'
    | '/pemilik/penghuni/choose-room'
    | '/pemilik/penghuni/created'
    | '/pemilik/penghuni/form'
    | '/penghuni/keluhan'
    | '/penghuni/profile'
    | '/penghuni/tagihan'
    | '/pemilik'
    | '/penghuni'
    | '/penghuni/onboarding'
  id:
    | '__root__'
    | '/_main'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_main/'
    | '/_main/pemilik/_main'
    | '/_main/penghuni/_main'
    | '/_auth/sign-up/form'
    | '/_auth/sign-up/ktp'
    | '/_main/pemilik/notification'
    | '/_main/penghuni/notification'
    | '/_auth/sign-up/'
    | '/_main/pemilik/_main/informasi'
    | '/_main/pemilik/_main/profile'
    | '/_main/pemilik/_main/tagihan'
    | '/_main/pemilik/penghuni/choose-room'
    | '/_main/pemilik/penghuni/created'
    | '/_main/pemilik/penghuni/form'
    | '/_main/penghuni/_main/keluhan'
    | '/_main/penghuni/_main/profile'
    | '/_main/penghuni/_main/tagihan'
    | '/_main/pemilik/_main/'
    | '/_main/penghuni/_main/'
    | '/_main/penghuni/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpFormRoute: typeof AuthSignUpFormRoute
  AuthSignUpKtpRoute: typeof AuthSignUpKtpRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/penghuni/notification': {
      id: '/_main/penghuni/notification'
      path: '/penghuni/notification'
      fullPath: '/penghuni/notification'
      preLoaderRoute: typeof MainPenghuniNotificationRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/pemilik/notification': {
      id: '/_main/pemilik/notification'
      path: '/pemilik/notification'
      fullPath: '/pemilik/notification'
      preLoaderRoute: typeof MainPemilikNotificationRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/sign-up/ktp': {
      id: '/_auth/sign-up/ktp'
      path: '/sign-up/ktp'
      fullPath: '/sign-up/ktp'
      preLoaderRoute: typeof AuthSignUpKtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up/form': {
      id: '/_auth/sign-up/form'
      path: '/sign-up/form'
      fullPath: '/sign-up/form'
      preLoaderRoute: typeof AuthSignUpFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/penghuni/_main': {
      id: '/_main/penghuni/_main'
      path: '/penghuni'
      fullPath: '/penghuni'
      preLoaderRoute: typeof MainPenghuniMainRouteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/pemilik/_main': {
      id: '/_main/pemilik/_main'
      path: '/pemilik'
      fullPath: '/pemilik'
      preLoaderRoute: typeof MainPemilikMainRouteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/penghuni/onboarding/': {
      id: '/_main/penghuni/onboarding/'
      path: '/penghuni/onboarding'
      fullPath: '/penghuni/onboarding/'
      preLoaderRoute: typeof MainPenghuniOnboardingIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/penghuni/_main/': {
      id: '/_main/penghuni/_main/'
      path: '/'
      fullPath: '/penghuni/'
      preLoaderRoute: typeof MainPenghuniMainIndexRouteImport
      parentRoute: typeof MainPenghuniMainRouteRoute
    }
    '/_main/pemilik/_main/': {
      id: '/_main/pemilik/_main/'
      path: '/'
      fullPath: '/pemilik/'
      preLoaderRoute: typeof MainPemilikMainIndexRouteImport
      parentRoute: typeof MainPemilikMainRouteRoute
    }
    '/_main/penghuni/_main/tagihan': {
      id: '/_main/penghuni/_main/tagihan'
      path: '/tagihan'
      fullPath: '/penghuni/tagihan'
      preLoaderRoute: typeof MainPenghuniMainTagihanRouteImport
      parentRoute: typeof MainPenghuniMainRouteRoute
    }
    '/_main/penghuni/_main/profile': {
      id: '/_main/penghuni/_main/profile'
      path: '/profile'
      fullPath: '/penghuni/profile'
      preLoaderRoute: typeof MainPenghuniMainProfileRouteImport
      parentRoute: typeof MainPenghuniMainRouteRoute
    }
    '/_main/penghuni/_main/keluhan': {
      id: '/_main/penghuni/_main/keluhan'
      path: '/keluhan'
      fullPath: '/penghuni/keluhan'
      preLoaderRoute: typeof MainPenghuniMainKeluhanRouteImport
      parentRoute: typeof MainPenghuniMainRouteRoute
    }
    '/_main/pemilik/penghuni/form': {
      id: '/_main/pemilik/penghuni/form'
      path: '/pemilik/penghuni/form'
      fullPath: '/pemilik/penghuni/form'
      preLoaderRoute: typeof MainPemilikPenghuniFormRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/pemilik/penghuni/created': {
      id: '/_main/pemilik/penghuni/created'
      path: '/pemilik/penghuni/created'
      fullPath: '/pemilik/penghuni/created'
      preLoaderRoute: typeof MainPemilikPenghuniCreatedRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/pemilik/penghuni/choose-room': {
      id: '/_main/pemilik/penghuni/choose-room'
      path: '/pemilik/penghuni/choose-room'
      fullPath: '/pemilik/penghuni/choose-room'
      preLoaderRoute: typeof MainPemilikPenghuniChooseRoomRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/pemilik/_main/tagihan': {
      id: '/_main/pemilik/_main/tagihan'
      path: '/tagihan'
      fullPath: '/pemilik/tagihan'
      preLoaderRoute: typeof MainPemilikMainTagihanRouteImport
      parentRoute: typeof MainPemilikMainRouteRoute
    }
    '/_main/pemilik/_main/profile': {
      id: '/_main/pemilik/_main/profile'
      path: '/profile'
      fullPath: '/pemilik/profile'
      preLoaderRoute: typeof MainPemilikMainProfileRouteImport
      parentRoute: typeof MainPemilikMainRouteRoute
    }
    '/_main/pemilik/_main/informasi': {
      id: '/_main/pemilik/_main/informasi'
      path: '/informasi'
      fullPath: '/pemilik/informasi'
      preLoaderRoute: typeof MainPemilikMainInformasiRouteImport
      parentRoute: typeof MainPemilikMainRouteRoute
    }
  }
}

interface MainPemilikMainRouteRouteChildren {
  MainPemilikMainInformasiRoute: typeof MainPemilikMainInformasiRoute
  MainPemilikMainProfileRoute: typeof MainPemilikMainProfileRoute
  MainPemilikMainTagihanRoute: typeof MainPemilikMainTagihanRoute
  MainPemilikMainIndexRoute: typeof MainPemilikMainIndexRoute
}

const MainPemilikMainRouteRouteChildren: MainPemilikMainRouteRouteChildren = {
  MainPemilikMainInformasiRoute: MainPemilikMainInformasiRoute,
  MainPemilikMainProfileRoute: MainPemilikMainProfileRoute,
  MainPemilikMainTagihanRoute: MainPemilikMainTagihanRoute,
  MainPemilikMainIndexRoute: MainPemilikMainIndexRoute,
}

const MainPemilikMainRouteRouteWithChildren =
  MainPemilikMainRouteRoute._addFileChildren(MainPemilikMainRouteRouteChildren)

interface MainPenghuniMainRouteRouteChildren {
  MainPenghuniMainKeluhanRoute: typeof MainPenghuniMainKeluhanRoute
  MainPenghuniMainProfileRoute: typeof MainPenghuniMainProfileRoute
  MainPenghuniMainTagihanRoute: typeof MainPenghuniMainTagihanRoute
  MainPenghuniMainIndexRoute: typeof MainPenghuniMainIndexRoute
}

const MainPenghuniMainRouteRouteChildren: MainPenghuniMainRouteRouteChildren = {
  MainPenghuniMainKeluhanRoute: MainPenghuniMainKeluhanRoute,
  MainPenghuniMainProfileRoute: MainPenghuniMainProfileRoute,
  MainPenghuniMainTagihanRoute: MainPenghuniMainTagihanRoute,
  MainPenghuniMainIndexRoute: MainPenghuniMainIndexRoute,
}

const MainPenghuniMainRouteRouteWithChildren =
  MainPenghuniMainRouteRoute._addFileChildren(
    MainPenghuniMainRouteRouteChildren,
  )

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainPemilikMainRouteRoute: typeof MainPemilikMainRouteRouteWithChildren
  MainPenghuniMainRouteRoute: typeof MainPenghuniMainRouteRouteWithChildren
  MainPemilikNotificationRoute: typeof MainPemilikNotificationRoute
  MainPenghuniNotificationRoute: typeof MainPenghuniNotificationRoute
  MainPemilikPenghuniChooseRoomRoute: typeof MainPemilikPenghuniChooseRoomRoute
  MainPemilikPenghuniCreatedRoute: typeof MainPemilikPenghuniCreatedRoute
  MainPemilikPenghuniFormRoute: typeof MainPemilikPenghuniFormRoute
  MainPenghuniOnboardingIndexRoute: typeof MainPenghuniOnboardingIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainPemilikMainRouteRoute: MainPemilikMainRouteRouteWithChildren,
  MainPenghuniMainRouteRoute: MainPenghuniMainRouteRouteWithChildren,
  MainPemilikNotificationRoute: MainPemilikNotificationRoute,
  MainPenghuniNotificationRoute: MainPenghuniNotificationRoute,
  MainPemilikPenghuniChooseRoomRoute: MainPemilikPenghuniChooseRoomRoute,
  MainPemilikPenghuniCreatedRoute: MainPemilikPenghuniCreatedRoute,
  MainPemilikPenghuniFormRoute: MainPemilikPenghuniFormRoute,
  MainPenghuniOnboardingIndexRoute: MainPenghuniOnboardingIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpFormRoute: AuthSignUpFormRoute,
  AuthSignUpKtpRoute: AuthSignUpKtpRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
